// <auto-generated />
using AppServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531155701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppServer.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("[varchar](50)");

                    b.Property<string>("CountryIsoCodeAlpha2")
                        .HasColumnType("[varchar](2)");

                    b.Property<string>("Make")
                        .HasColumnType("[varchar](50)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("MileageUnit")
                        .HasColumnType("[varchar](10)");

                    b.Property<string>("Model")
                        .HasColumnType("[varchar](50)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasColumnType("[varchar](50)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("[varchar](17)");

                    b.HasKey("Id");

                    b.ToTable("Vehicle", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            CountryIsoCodeAlpha2 = "FR",
                            Make = "BMW",
                            Mileage = 4500,
                            MileageUnit = "KM",
                            Model = "Serie 1",
                            ModelYear = 2023,
                            Price = 25000,
                            Version = "abc1",
                            Vin = "JH4CU2E46CC854694"
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            CountryIsoCodeAlpha2 = "DE",
                            Make = "AUDI",
                            Mileage = 26000,
                            MileageUnit = "KM",
                            Model = "A4",
                            ModelYear = 2019,
                            Price = 18500,
                            Version = "efg2",
                            Vin = "GV4CU2E56TT854647"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
